### PR TITLE
NtMaker configuration file

### PR DESCRIPTION
**Pull request by gerbaudo**
Matt's G. suggestion: try to have a "configuration file" for NtMaker.
This could be useful for example to turn on/off trigger branches;
it'd also be useful to clarify all the options that we already have for NtMaker.
It can be implemented quite easily with a little python wrapper
around NtMaker, with a json/python config.

### CODE REVIEW

**Comment by gerbaudo** [comment]
This is just an initial version of the configurable `NtMaker` driver
we discussed on Mon. I think we have two options, both based
on the capability of optparse to store the defaults to a file, see:
http://stackoverflow.com/questions/1880404/using-a-file-to-store-optparse-arguments

These are:

1. write a wrapper that calls the existing NtMaker.cxx.
Advantages:
  - it will work right away, python is just taking the cmd line options and
    making a system call. Disadvantages:
  - add another layer hiding the NtMaker options, making things
   more difficult to debug (esp on the grid)
  - the current NtMaker options and their c++ parsing are clunky,
    and they could benefit from some cleanup

2. write a python script that instantiate a SusyNtMaker object
and configures it.
Advantages:
- cleaner solution, does not pass options from one script to
  another executable
- can do the guesswork (e.g. explore the metadata and set
  some of the defaults accordingly) in python, which is easier
  since it's mostly string parsing and manipulation
Disadvantages:
  - xaod access from pyroot is not very stable yet (but it will be
   there, people are pushing for it)

The `NtMaker.py` I pushed is an example of option 2.
It mostly works, but it needs some cleanup and adjustments.
I believe that @dantrim has some skeleton example for option 1.
We should discuss what seems more sensible.

**Comment by sparticlesteve** [comment]
Well, optparse is deprecated. Why not use argparse?
I would suggest avoiding setting up the xAOD access in python and then using it in C++ code. You should be able to wrap any needed functionality in C++ (like creating/attaching the event stores), and still use python as your steering script.

**Comment by gerbaudo** [comment]
Thanks for the input, @sparticlesteve !
You're right, there's no reason not to use argparse.
I just used an example I had handy...I'll change it :-)
Regarding the xAOD access: I am still
using `SusyNtMaker`, so everything that's
xAOD access is still happening in c++.
The only thing that's done in python is the
of the `TChain` that's fed to the TSelector.
Does this sound like a reasonable solution
to you?

**Comment by sparticlesteve** [comment]
yeah, that sounds fine

**Pull request closed without merging**
