### PR TITLE
Xaod muon sf

### PR DESCRIPTION
**Pull request by gerbaudo**
Addressing #57

### CODE REVIEW

**Comment by gerbaudo** [comment]
Since this requires a change in the ntuple format,
see gerbaudo/SusyNtuple#60 , I would not include
it in `n0205`. We can include these changes in the
next production, when we'll address more syst
variations.

**Comment by amete** [comment]
Hi Davide, 

Thanks and sorry for the slow response on this. I think it's mostly OK. Do I understand correctly that like electrons, we're storing different muon ids, loose, medium, tight etc.? In the current scheme, we have one instance of SUSYTools for electron id that we store, in principle shouldn't we do the same for muons as well? Then for the scale factors, we can do the same and store the SF for the tightest quality that a muon passes. Could you comment? Many thanks.

Best,
Serhan

**Comment by gerbaudo** [comment]
Hi @amete 
I think that the solution implemented by @dantrim for the electrons is fine.
In that case, the reason for having multiple `SUSYTools` instances is that
the electron tool cannot be re-configured for different IDs; perhaps the muon
tool can be reconfigured and doesn't require another instance of `SUSYTools`?

**Comment by dantrim** [comment]
Hi @gerbaudo @amete 
I think the only place that we really use the different instances of the SUSYTools is when we grab the scale factors for the electrons, correct? For muons, the scale-factor configuration file is the same for all muon IDs, as opposed to the electron case, so I was originally thinking that we did not have to implement the combinatorics of instantiating an ST object per muon ID. 

In the latest tags of SUSYTools I believe they took our advice and now the tools are configurable per ID point. I have not looked into it yet, but this maybe removes the requirement of having to initialize so many tools on our end?

**Comment by amete** [comment]
Hi guys,

So testing to see if xaod_muonSF works over MC15 actually requires to update the SUSYTools version. I confirm that the current implementation works in DC14 w/o any issues. Therefore, I'm merging xaod_muonSF into xaod so that we can mover forward. When we update the SUSYTools if we see that this becomes a problem, then we can deal w/ that later on. As the code stands right now we store the tightest ID SF for electrons, and for muons we get the SF that is returned for the signal muon as is defined within SUSYTools (i.e. medium).

Best,
Serhan

**Comment by dantrim** [comment]
It looks like you've initialized a muonSelection tool configured for veryLoose. This tool is already initalized below this (we have the 4 muon id's for this tool being initialized). 

This again leads back to the question: If we want to store multiple SF's rather than the tightest and then grab the corresponding one for the quality of the object we choose? It seems like we initialize 5 instances of ST only for these SF's for electrons, so should we just store the SF for each ID (e.g. SF_mediumLLH, SF_tightLLH). This way when switchign ele ID we can switch the SF. We could then do this for muons. As we we store only the loosest objects (i.e. m_preElectrons, m_preMuons, etc...) in the output ntuple I think this is OK. 

Also, in the latest version of ST (06-10), the muonSF tool is now configured depending on the muon ID (tight, medium, loose) whereas in DC14 there was only a single way to configure this tool, so if we want flexibility on the muon side should wepossibly store the multiple SF's? (there is only one tool per ID for muons whereas for electrons there is the ID, reco, and trig SF tool for each working point, so for muons this may not be so painful).

**Pull request merged**
